export const soccerAll = {
  fulltimeResult: {
    marketname: "Fulltime Result",
    suspend: "0",
    header: [],
    rows: [],
  },
  toQualify: {
    marketname: "To Qualify",
    suspend: "0",
    header: [],
    rows: [],
  },
  doubleChance: {
    marketname: "Double Chance",
    suspend: "0",
    header: [],
    rows: [],
  },
  goalsOverUnder: {
    marketname: "Goals Over/Under",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  toWintheTrophy: {
    marketname: "To Win the Trophy",
    suspend: "0",
    header: [],
    rows: [],
  },
  halfTimeResult: {
    marketname: "Half Time Result",
    suspend: "0",
    header: [],
    rows: [],
  },
  nthGoal: {
    marketname: "nth Goal",
    suspend: "0",
    header: [],
    rows: [],
  },
  matchGoals: {
    marketname: "Match Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  alternativematchGoals: {
    marketname: "Alternative Match Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  gameWonInExtraTime: {
    marketname: "Game Won In Extra Time",
    suspend: "0",
    header: [],
    rows: [],
  },
  gameWonAfterPenaltiesShootout: {
    marketname: "Game Won After Penalties Shootout",
    suspend: "0",
    header: [],
    rows: [],
  },
  matchCorners: {
    marketname: "Match Corners",
    currentCorners: "",
    firstCellBorderRight: true,
    suspend: "0",
    header: ["", "Over", "Exactly", "Under"],
    rows: [],
  },
  twoWayCorners: {
    marketname: "2-Way Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfGoals: {
    marketname: "First Half Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  asianHandicap: {
    marketname: "Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  goalLine: {
    marketname: "Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsianHandicap: {
    marketname: "1st Half Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  firstHalfGoalLine: {
    marketname: "1st Half Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  halfTimeFullTime: {
    marketname: "Half Time/Full Time",
    suspend: "0",
    header: [],
    rows: [],
  },
  halfTimeCorrectScore: {
    marketname: "Half Time Correct Score",
    suspend: "0",
    header: ["1", "x", "2"],
    rows: [],
  },
  correctScore: {
    marketname: "Correct Score",
    suspend: "0",
    header: ["Home", "Draw", "Away"],
    rows: [],
  },
  finalScore: {
    marketname: "Final Score",
    suspend: "0",
    header: ["1", "x", "2"],
    rows: [],
  },
  asianCorners: {
    marketname: "Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsianCorners: {
    marketname: "First Half Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  cornerRace: {
    marketname: "Corner Race",
    suspend: "0",
    firstCellBorderRight: true,
    header: ["", "Home", "Away", "Neither"],
    rows: [],
  },
  corners: {
    marketname: "Corners",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "3-WayHandicap": {
    marketname: "3-Way Handicap",
    suspend: "0",
    header: ["Home", "Draw", "Away"],
    rows: [],
  },
  firstHalfHandicap: {
    marketname: "1st Half - Handicap",
    suspend: "0",
    header: ["Home", "Draw", "Away"],
    rows: [],
  },
  drawNoBet: {
    marketname: "Draw No Bet",
    suspend: "0",
    header: [],
    rows: [],
  },
  handicapResult: {
    marketname: "Handicap Result",
    suspend: "0",
    header: ["Home", "Tie", "Away"],
    rows: [],
  },
  alternativeHandicapResult: {
    marketname: "Alternative Handicap Result",
    suspend: "0",
    header: ["Home", "Tie", "Away"],
    rows: [],
  },
  lastTeamToScore: {
    marketname: "Last Team to Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  goalOddEven: {
    marketname: "Goals Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
  toWin2ndHalf: {
    marketname: "To Win 2nd Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  resultBothTeamsToScore: {
    marketname: "Result / Both Teams To Score",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  bothTeamsToScore: {
    marketname: "Both Teams to Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScoreFirstHalf: {
    marketname: "Both Teams To Score (1st Half)",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScoreSecondHalf: {
    marketname: "Both Teams To Score (2nd Half)",
    suspend: "0",
    header: [],
    rows: [],
  },
  teamCleanSheet: {
    marketname: "Team Clean Sheet",
    suspend: "0",
    header: ["Home"],
    rows: [],
  },
  homeGoals: {
    marketname: "Home Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  awayGoals: {
    marketname: "Away Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
};
// ["Result", "Double Chance", "Match Goals", "Next Goal", "Score", "Goals Odd/Even"]

export const soccerBetBuilder = {
  result: {
    marketname: "Result",
    suspend: "0",
    header: ["", "Home", "Draw", "Away"],
    rows: [],
  },
  bothTeamsToScore: {
    marketname: "Both Teams To Score",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  doubleChance: {
    marketname: "Double Chance",
    suspend: "0",
    header: [],
    rows: [],
  },
  matchGoals: {
    marketname: "Match Goals",
    suspend: "0",
    subtabs: ["Match", "1st Half", "2nd Half"],
    header: [],
    "Match header": ["", "Over", "Under"],
    Match: [],
    "1st Half header": ["", "Over", "Under"],
    "1st Half": [],
  },
  nextGoal: {
    marketname: "Next Goal",
    suspend: "0",
    header: [],
    rows: [],
  },
  corners: {
    marketname: "Corners",
    suspend: "0",
    subtabs: ["Match"],
    header: [],
    "Match header": ["", "Over", "Exactly", "Under"],
    Match: [],
  },
  teamGoals: {
    marketname: "Team Goals",
    suspend: "0",
    subtabs: ["Home", "Away"],
    header: [],
    "Home header": ["", "Over", "Under"],
    Home: [],
    Away: [],
    "Away header": ["", "Over", "Under"],
  },
  score: {
    marketname: "Score",
    suspend: "0",
    subtabs: ["Full Time Score"],
    header: [],
    "Full Time Score header": ["Home", "Draw", "Away"],
    "Full Time Score": [],
  },
  tenminmarkets: {
    marketname: "10 Minute Markets",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  goalOddEven: {
    marketname: "Goals - Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
  teamToScorein2ndHalf: {
    marketname: "Team To Score in 2nd Half",
    suspend: "0",
    header: ["", "Score", "Not Score"],
    rows: [],
  },
  teamToScoreinBothHalf: {
    marketname: "Team To Score in Both Half",
    suspend: "0",
    header: ["", "Score", "Not Score"],
    rows: [],
  },
};
export const soccerAsianLines = {
  asianHandicap: {
    marketname: "Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  goalLine: {
    marketname: "Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsianHandicap: {
    marketname: "1st Half Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  firstHalfGoalLine: {
    marketname: "1st Half Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
};
export const soccerCornersCards = {
  matchCorners: {
    marketname: "Match Corners",
    currentCorners: "",
    firstCellBorderRight: true,
    suspend: "0",
    header: ["", "Over", "Exactly", "Under"],
    rows: [],
  },
  twoWayCorners: {
    marketname: "2-Way Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  asianCorners: {
    marketname: "Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsianCorners: {
    marketname: "First Half Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  cornerRace: {
    marketname: "Corner Race",
    suspend: "0",
    firstCellBorderRight: true,
    header: ["", "Home", "Away", "Neither"],
    rows: [],
  },
  corners: {
    marketname: "Corners",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
};

export const soccerGoals = {
  nthGoal: {
    marketname: "nth Goal",
    suspend: "0",
    header: [],
    rows: [],
  },
  matchGoals: {
    marketname: "Match Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  alternativematchGoals: {
    marketname: "Alternative Match Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  lastTeamToScore: {
    marketname: "Last Team to Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  goalOddEven: {
    marketname: "Goals Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
};

export const soccerHalf = {
  halfTimeResult: {
    marketname: "Half Time Result",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstHalfGoals: {
    marketname: "First Half Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsianHandicap: {
    marketname: "1st Half Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  firstHalfGoalLine: {
    marketname: "1st Half Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  halfTimeFullTime: {
    marketname: "Half Time/Full Time",
    suspend: "0",
    header: [],
    rows: [],
  },
  halfTimeCorrectScore: {
    marketname: "Half Time Correct Score",
    suspend: "0",
    header: ["1", "x", "2"],
    rows: [],
  },
  firstHalfAsianCorners: {
    marketname: "First Half Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfHandicap: {
    marketname: "1st Half - Handicap",
    suspend: "0",
    header: ["Home", "Draw", "Away"],
    rows: [],
  },
  toWin2ndHalf: {
    marketname: "To Win 2nd Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScoreSecondHalf: {
    marketname: "Both Teams To Score (2nd Half)",
    suspend: "0",
    header: [],
    rows: [],
  },
};
