export const details = {
    "Lines": [
        "Game Lines",
        "5 Innings",
        "3-Way"
    ],
    "Main Props": [
        "Run Line and Total ",
        "Money Line and Total ",
        "Money Line and Alternative Total",
        "Alternative Run Line",
        "Alternative Game Total",
        "Alternative 3-Way Run Line",
        "Alternative 3-Way Total",
        "First Home Run of Game Will be",
        "Winning Margins",
        "Double Result",
        "Race To (Runs)",
        "Total Hits",
        "Alternative Total Hits",
        "Most Hits",
        "Race to (Hits)",
        "Match Correct Score",
        "Highest Scoring Period",
        "Extra Innings",
        "Game Totals - Bands",
        "Game Total Odd/Even",
    ],
    "Player Props": [
        "Pitcher Outs",
        "Pitcher Strikeouts",
        "Pitcher Strikeouts Milestones",
        "Pitcher to Record the Win",
        "Pitcher Earned Runs",
        "Pitcher Hits Allowed",
        "Pitcher Walks Issued",
        "Player Runs",
        "Player Runs Milestones",
        "Player Home Runs",
        "Player Home Runs Milestones",
        "Player Hits",
        "Player Hits Milestones",
        "Player Singles",
        "Player Doubles",
        "Player Triples",
        "Player Runs Batted In",
        "Player Runs Batted In Milestones",
        "Player Total Bases",
        "Player Total Bases Milestones",
        "Player Total Bases Match-Ups",
        "Player Stolen Bases",
        "Pitcher to Record First Strikeout",
    ],
    "Innings Props": [
        "1st Inning Winner",
        "A Run in the 1st Inning",
        "1st Inning Runs ",
        "Most Hits in the 1st Inning",
        "1st Inning Total Hits",
        "3 Innings",
        "4 1/2 Innings",
        "7 Innings",
        "Alternative 3 Innings Line",
        "Alternative 3 Innings Totals",
        "Alternative 5 Innings Line",
        "Alternative 5 Innings Total",
        "Alternative 7 Innings Line",
        "A Run in the Top of the 1st",
        "Alternative 7 Innings Totals",
        "A Hit in the Top of the 1st",
        "Any Batter to Reach Base in the Top of the 1st",
        "Back to Back Hits in the Top of the 1st",
        "A Run in the Bottom of the 1st",
        "A Hit in the Bottom of the 1st",
        "Any Batter to Reach Base in the Bottom of the1st",
        "Back to Back Hits in the Bottom of the 1st"
    ],
    "Team Props": [
        "Team Scoring First Wins Game",
        "First Team to Score",
        "Last Team to Score",
        "Both Teams to Score 'X' Runs",
        "Lead After (Innings)",
        "Team with Highest Scoring Inning",
        "Team Totals",
        "Team Alternative Totals",
        "Team Hits",
        "Team Alternative Hits",
        "Team Total Odd/Even",
    ],
    "Game Props": [] as any,
}
