export const hockeyMain = {
  toWinMatch: {
    marketname: "To Win Match",
    suspend: "0",
    rows: [],
  },
  matchHandicapGames: {
    marketname: "Match Handicap (Games)",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  "totalGames2-Way": {
    marketname: "Total Games 2-Way",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  setBetting: {
    marketname: "Set Betting",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  firstSetWinner: {
    marketname: "First Set Winner",
    suspend: "0",
    header: [],
    rows: [],
  },
  "1stSetTotalGames": {
    marketname: "1st Set Total Games",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstSetScore: {
    marketname: "First Set Score",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  matchResultAndTotalGames: {
    marketname: "Match Result and Total Games",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  homeTo: {
    marketname: "Home To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstHomeServiceGame-Winners": {
    marketname: "First Home Service Game - Winners",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstHomeServiceGame-Score": {
    marketname: "First Home Service Game - Score",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstHomeServiceGame-ToWinTo": {
    marketname: "First Home Service Game - To Win To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  awayTo: {
    marketname: "Away To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstAwayServiceGame-Winners": {
    marketname: "First Away Service Game - Winners",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstAwayServiceGame-Score": {
    marketname: "First Away Service Game - Score",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstAwayServiceGame-ToWinTo": {
    marketname: "First Away Service Game - To Win To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  goTheDistance: {
    marketname: "Go The Distance?",
    suspend: "0",
    header: [],
    rows: [],
  },
};

export const hockeyBetBuilder = {
  "match/SetWinner": {
    marketname: "Match/Set Winner",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  aceTotals: {
    marketname: "Ace Totals",
    suspend: "0",
    subtabs: ["Milestones"],
    header: [],
    "Milestones header": ["", "Home", "Away", "Match"],
    Milestones: [],
  },
  totalGamesInSet: {
    marketname: "Total Games in Set",
    suspend: "0",
    subtabs: ["Set 1"],
    header: [],
    "Set 1 header": ["", "Over", "Under"],
    "Set 1": [],
  },
  playerToWinASet: {
    marketname: "Player To Win a Set",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "player1stServiceGame-GameWinner": {
    marketname: "Player 1st Service Game - Game Winner",
    suspend: "0",
    header: [],
    rows: [],
  },
  setBetting: {
    marketname: "Set Betting",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  set1CorrectScoreGroup: {
    marketname: "Set 1 Correct Score Group",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  setGameScore: {
    marketname: "Set Game Score",
    suspend: "0",
    subtabs: ["Set 1", "Set 2", "Set 3"],
    header: [],
    "Set 1 header": ["", "Home", "Away", "Either"],
    "Set 1": [],
    "Set 2 header": ["", "Home", "Away"],
    "Set 2": [],
    "Set 3 header": ["", "Home", "Away"],
    "Set 3": [],
  },
  breaksOfServe: {
    marketname: "Breaks of Serve",
    suspend: "0",
    subtabs: ["Total", "Set 1", "Set 1 to Break Serve"],
    header: [],
    "Total header": ["", "Over", "Under"],
    Total: [],
    "Set 1 header": ["", "Over", "Under"],
    "Set 1": [],
    "Set 1 to Break Serve header": ["", "Home", "Away"],
    "Set 1 to Break Serve": [],
  },
  playerSpecials: {
    marketname: "Player Specials",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  doubleFaultTotals: {
    marketname: "Double Fault Totals",
    suspend: "0",
    subtabs: ["Milestones"],
    header: [],
    "Milestones header": ["", "Home", "Away", "Match"],
    Milestones: [],
  },
  matchSpecials: {
    marketname: "Match Specials",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "player1stAce/Break": {
    marketname: "Player 1st Ace/Break",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  matchTotalTieBreaks: {
    marketname: "Match Total Tie Breaks",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  "match/SetHandicapGames": {
    marketname: "Match/Set Handicap (Games)",
    suspend: "0",
    subtabs: ["Match", "Set 1"],
    header: [],
    "Match header": ["Home", "Away"],
    Match: [],
    "Set 1 header": ["Home", "Away"],
    "Set 1": [],
  },
  matchTotalSets: {
    marketname: "Match Total Sets",
    suspend: "0",
    header: [],
    rows: [],
  },
  "setRaceTo/LeadAfter": {
    marketname: "Set Race To/Lead After",
    suspend: "0",
    subtabs: ["Race To", "Lead Ater"],
    header: [],
    "Race To header": ["", "Home", "Away"],
    "Race To": [],
    "Lead After header": ["", "Home", "Away", "Tie"],
    "Lead After": [],
  },
  set1ScoreAfterGames: {
    marketname: "Set 1 Score After (Games)",
    suspend: "0",
    subtabs: ["Score After 4 Games", "Score After 6 Games"],
    header: [],
    "Score After 4 Games header": ["", "Home", "Away"],
    "Score After 4 Games": [],
    "Score After 6 Games header": ["", "Home", "Away"],
    "Score After 6 Games": [],
  },
  "player1stServiceGame-Handicap": {
    marketname: "Player 1st Service Game - Handicap",
    suspend: "0",
    header: [],
    rows: [],
  },
  "player1stServiceGame-ToFaceBreakPoint": {
    marketname: "Player 1st Service Game - To Face Break Point",
    suspend: "0",
    header: [],
    rows: [],
  },
  "player1stServiceGame-GoToDeuce": {
    marketname: "Player 1st Service Game - Go To Deuce",
    suspend: "0",
    header: [],
    rows: [],
  },
  "player1stServiceGame-TotalPoints": {
    marketname: "Player 1st Service Game - Total Points",
    suspend: "0",
    header: [],
    rows: [],
  },
};

export const hockeySet = {
  firstSetWinner: {
    marketname: "First Set Winner",
    suspend: "0",
    header: [],
    rows: [],
  },
  setBetting: {
    marketname: "Set Betting",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "1stSetTotalGames": {
    marketname: "1st Set Total Games",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstSetScore: {
    marketname: "First Set Score",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  firstSethandicap: {
    marketname: "First Set Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  firstSetCorrectScoreGroup: {
    marketname: "First Set Correct Score Group",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  firstSetScoreAnyPlayer: {
    marketname: "First Set Score Any Player",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstSetPlayerToBreakServe: {
    marketname: "First Set Player To Break Serve",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
};

export const hockeyGames = {
  matchHandicapGames: {
    marketname: "Match Handicap (Games)",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  "totalGames2-Way": {
    marketname: "Total Games 2-Way",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  "1stSetTotalGames": {
    marketname: "1st set Total Games",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstBreakOfServe: {
    marketname: "First Break Of Serve",
    suspend: "0",
    header: [],
    rows: [],
  },
  matchResultAndTotalGames: {
    marketname: "Match Result and Total Games",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
};

export const hockeyPlayer = {
  firstSetPlayerToBreakServe: {
    marketname: "First Set Player To Break Serve",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  homeTo: {
    marketname: "Home To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstHomeServiceGame-Winners": {
    marketname: "First Home Service Game - Winners",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstHomeServiceGame-Score": {
    marketname: "First Home Service Game - Score",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstHomeServiceGame-ToWinTo": {
    marketname: "First Home Service Game - To Win To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstHomeServiceGame-Yes/No": {
    marketname: "First Home Service Game - Yes/No",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstHomeServiceGame-TotalPoints": {
    marketname: "First Home Service Game - Total Points",
    suspend: "0",
    header: [],
    rows: [],
  },
  awayTo: {
    marketname: "Away To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstAwayServiceGame-Winners": {
    marketname: "First Away Service Game - Winners",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstAwayServiceGame-Score": {
    marketname: "First Away Service Game - Score",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "firstAwayServiceGame-ToWinTo": {
    marketname: "First Away Service Game - To Win To",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstAwayServiceGame-Yes/No": {
    marketname: "First Away Service Game - Yes/No",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "firstAwayServiceGame-TotalPoints": {
    marketname: "First Away Service Game - Total Points",
    suspend: "0",
    header: [],
    rows: [],
  },
};
