export const soccerAll = {
  fulltimeResult: {
    marketname: "Fulltime Result",
    suspend: "0",
    header: [],
    rows: [],
  },
  doubleChance: {
    marketname: "Double Chance",
    suspend: "0",
    header: [],
    rows: [],
  },
  goalsOverUnder: {
    marketname: "Goals Over/Under",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  bothTeamsToScore: {
    marketname: "Both Teams to Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  resultBothTeamsToScore: {
    marketname: "Result / Both Teams To Score",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  correctScore: {
    marketname: "Correct Score",
    suspend: "0",
    header: ["Home", "Draw", "Away"],
    rows: [],
  },
  halfTimeFullTime: {
    marketname: "Half Time/Full Time",
    suspend: "0",
    header: [],
    rows: [],
  },
  halfTimeCorrectScore: {
    marketname: "Half Time/Full Time Correct Score",
    suspend: "0",
    header: ["1", "x", "2"],
    rows: [],
  },
  goalscorers: {
    marketname: "Goalscorers",
    suspend: "0",
    header: ["", "First", "Last", "Anytime"],
    rows: [],
  },
  asianHandicap: {
    marketname: "Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  goalLine: {
    marketname: "Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  drawNoBet: {
    marketname: "Draw No Bet",
    suspend: "0",
    header: [],
    rows: [],
  },
  totalCorners3way: {
    marketname: "Corners",
    currentCorners: "",
    firstCellBorderRight: true,
    suspend: "0",
    header: ["", "Over", "Exactly", "Under"],
    rows: [],
  },
  handicapResult: {
    marketname: "Handicap Result",
    suspend: "0",
    header: ["Home", "Tie", "Away"],
    rows: [],
  },
  alternativeHandicapResult: {
    marketname: "Alternative Handicap Result",
    suspend: "0",
    header: ["Home", "Tie", "Away"],
    rows: [],
  },
};
// ["Result", "Double Chance", "Match Goals", "Next Goal", "Score", "Goals Odd/Even"]

export const soccerBetBuilder = {
  result: {
    marketname: "Result",
    suspend: "0",
    header: ["", "Home", "Draw", "Away"],
    rows: [],
  },
  bothTeamsToScore: {
    marketname: "Both Teams To Score",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  doubleChance: {
    marketname: "Double Chance",
    suspend: "0",
    header: [],
    rows: [],
  },
  halftimeFulltime: {
    marketname: "Half Time/FullTime",
    suspend: "0",
    header: [],
    rows: [],
  },
  score: {
    marketname: "Score",
    suspend: "0",
    subtabs: ["Full Time Score", "Half Time Score"],
    header: [],
    "Full Time Score header": ["Home", "Draw", "Away"],
    "Full Time Score": [],
    "Half Time Score header": ["Home", "Draw", "Away"],
    "Half Time Score": [],
  },
  halfWithMostGoals: {
    marketname: "Half With Most Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  teamSpecials: {
    marketname: "Team Specials",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  winningMargin: {
    marketname: "Winning Margin",
    suspend: "0",
    subtabs: ["Match", "1st Half", "2nd Half", "First 10 Minutes"],
    header: [],
    "Match header": ["Home", "Either Team", "Away"],
    Match: [],
    "1st Half header": ["Home", "Either Team", "Away"],
    "1st Half": [],
    "2nd Half header": ["Home", "Either Team", "Away"],
    "2nd Half": [],
    "First 10 Minutes header": ["Home", "Either Team", "Away"],
    "First 10 Minutes": [],
  },
  goalOddEven: {
    marketname: "Goals - Odd/Even",
    suspend: "0",
    header: ["", "Odd", "Even"],
    rows: [],
  },
};
export const soccerAsianLines = {
  asianHandicap: {
    marketname: "Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  goalLine: {
    marketname: "Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  alternativeAsianHandicap: {
    marketname: "Alternative Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativeGoalLine: {
    marketname: "Alternative Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsianHandicap: {
    marketname: "1st Half Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  firstHalfGoalLine: {
    marketname: "1st Half Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  alternativeFirstHalfAsianHandicap: {
    marketname: "Alternative 1st Half Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativeFirstHalfGoalLine: {
    marketname: "Alternative 1st Half Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  asianTotalCorners: {
    marketname: "Asian Total Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  asianHandicapCorners: {
    marketname: "Asian Handicap Corners",
    suspend: "0",
    header: ["Over", "Under"],
    rows: [],
  },
  firstHalfAsianCorners: {
    marketname: "1st Half Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
};
export const soccerCornersCards = {
  matchCorners: {
    marketname: "Match Corners",
    currentCorners: "",
    firstCellBorderRight: true,
    suspend: "0",
    header: ["", "Over", "Exactly", "Under"],
    rows: [],
  },
  twoWayCorners: {
    marketname: "2-Way Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  asianCorners: {
    marketname: "Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsianCorners: {
    marketname: "First Half Asian Corners",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  cornerRace: {
    marketname: "Corner Race",
    suspend: "0",
    firstCellBorderRight: true,
    header: ["", "Home", "Away", "Neither"],
    rows: [],
  },
  corners: {
    marketname: "Corners",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
};

export const soccerGoals = {
  goalsOverUnder: {
    marketname: "Goals Over/Under",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  alternativetotalGoals: {
    marketname: "Alternative Total Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  resultTotalGoals: {
    marketname: "Result / Total Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  totalGoalsBothTeamsToScore: {
    marketname: "Total Goals/Both Teams to Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  exactTotalGoals: {
    marketname: "Exact Total Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  numberOfGoalsInMatch: {
    marketname: "Number of Goals In Match",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScore: {
    marketname: "Both Teams To Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  teamsToScore: {
    marketname: "Teams To Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScoreIn1stHalf: {
    marketname: "Both Teams To Score in 1st Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScoreIn2ndHalf: {
    marketname: "Both Teams To Score in 2nd Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstHalfGoals: {
    marketname: "First Half Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  exactFirstHalfGoals: {
    marketname: "Exact First Half Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  totalGoalMinutes: {
    marketname: "Total Goal Minutes 3 - Way",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstTeamToScore: {
    marketname: "First Team to Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstGoalMethod: {
    marketname: "First Goal Method",
    suspend: "0",
    header: [],
    rows: [],
  },
  earlyGoal: {
    marketname: "Early Goal",
    suspend: "0",
    header: [],
    rows: [],
  },
  lateGoal: {
    marketname: "Late Goal",
    suspend: "0",
    header: [],
    rows: [],
  },
  timeOfFirstGoalBrackets: {
    marketname: "Time of First Goal Brackets",
    suspend: "0",
    header: [],
    rows: [],
  },
  secondHalfGoals: {
    marketname: "Second Half Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  exactSecondHalfGoals: {
    marketname: "Exact Second Half Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  halfWithMostGoals: {
    marketname: "Half With Most Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  homeTeamHighestScoringHalf: {
    marketname: "Home Team Highest Scoring Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  awayTeamHighestScoringHalf: {
    marketname: "Away Team Highest Scoring Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  cleanSheet: {
    marketname: "Clean Sheet",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  teamTotalGoals: {
    marketname: "Clean Sheet",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  homeTeamExactGoals: {
    marketname: "Home Team Exact Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  awayTeamExactGoals: {
    marketname: "Away Team Exact Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  winningMargin: {
    marketname: "Winning Margin",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  timeOfFirstTeamGoal: {
    marketname: "Time of 1st Team Goal",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  goalOddEven: {
    marketname: "Goals Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
  homeTeamOddEvenGoals: {
    marketname: "Home Team Odd/Even Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  awayTeamOddEvenGoals: {
    marketname: "Away Team Odd/Even Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstHalfGoalsOddEven: {
    marketname: "1st Half Goals Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
  lastTeamtoScore: {
    marketname: "Last Team to Score",
    suspend: "0",
    header: [],
    rows: [],
  },
  first10Minutes: {
    marketname: "First 10 Minute (00:00 - 09:59)",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
};

export const soccerHalf = {
  halfTimeResult: {
    marketname: "Half Time Result",
    suspend: "0",
    header: [],
    rows: [],
  },
  halfTimeDoubleChance: {
    marketname: "Half Time Double Chance",
    suspend: "0",
    header: [],
    rows: [],
  },
  halfTimeResultBothTeamsToScore: {
    marketname: "Half Time Result/Both Teams To Score",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  halfTimeResultTotalGoals: {
    marketname: "Half Time Result/Total Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  halfTimeCorrectScore: {
    marketname: "Half Time Correct Score",
    suspend: "0",
    header: ["Home", "Draw", "Away"],
    rows: [],
  },
  bothTeamsToScorein1stHalf: {
    marketname: "Both Team To Score in 1st Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScorein2ndHalf: {
    marketname: "Both Team To Score in 2nd Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  bothTeamsToScorein1stHalf2ndHalf: {
    marketname: "Both Teams to Score 1st Half - 2nd Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstHalfAsianHandicap: {
    marketname: "1st Half Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  firstHalfGoalLine: {
    marketname: "1st Half Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  alternativeFirstHalfAsianHandicap: {
    marketname: "Alternative 1st Half Asian Handicap",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativeFirstHalfGoalLine: {
    marketname: "Alternative 1st Half Goal Line",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  firstHalfAsian3Way: {
    marketname: "1st Half Handicap 3-Way",
    suspend: "0",
    header: ["Home", "Tie", "Away"],
    rows: [],
  },
  alternativeFirstHalfHandicapResult: {
    marketname: "Alternative 1st Half Handicap Result",
    suspend: "0",
    header: ["Home", "Tie", "Away"],
    rows: [],
  },
  firstHalfGoals: {
    marketname: "First Half Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  exactFirstHalfGoals: {
    marketname: "Exact First Half Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  firstHalfCorners: {
    marketname: "First Half Corners",
    suspend: "0",
    header: ["", "Over", "Exactly", "Under"],
    rows: [],
  },
  firstHalfGoalsOddEven: {
    marketname: "1st Half Goals Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
  homeToScoreInHalf: {
    marketname: "Home Team To Score in Half",
    suspend: "0",
    header: ["Home", "Yes", "No"],
    rows: [],
  },
  awayToScoreInHalf: {
    marketname: "Away Team To Score in Half",
    suspend: "0",
    header: ["Away", "Yes", "No"],
    rows: [],
  },
  halfWithMostGoals: {
    marketname: "Half With Most Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  homeTeamHighestScoringHalf: {
    marketname: "Home Team Highest Scoring Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  awayTeamHighestScoringHalf: {
    marketname: "Away Team Highest Scoring Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  secondHalfResult: {
    marketname: "Away Team Highest Scoring Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  secondHalfGoals: {
    marketname: "Second Half Goals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  exactSecondHalfGoals: {
    marketname: "Exact Second Half Goals",
    suspend: "0",
    header: [],
    rows: [],
  },
  secondHalfGoalsOddEven: {
    marketname: "2nd Half Goals Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
};

export const soccerSpecials = {
  specials: {
    marketname: "Specials",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  toScoreInHalf: {
    marketname: "To Score in Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  toScoreaPenalty: {
    marketname: "To Score a Penalty",
    suspend: "0",
    header: [],
    rows: [],
  },
  toMissaPenalty: {
    marketname: "To Miss a Penalty",
    suspend: "0",
    header: [],
    rows: [],
  },
};

export const soccerMinutes = {
  "10MinuteResult": {
    marketname: "10 Minute Result",
    suspend: "0",
    header: [],
    rows: [],
  },
  first10Minutes: {
    marketname: "First 10 Minute (00:00 - 09:59)",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
};

// "boxing",
//     "esports",
//     "table_tennis",
//     "darts",
//     "soccer",
//     "basketball",
//     "tennis",
//     "hockey",
//     "handball",
//     "volleyball",
//     "baseball",
//     "cricket"
