export const details = {
    "Main": [
        "To Win Match",
        "Handicap 2-Way - Games Won",
        "Total Games 2-Way",
        "Set Betting",
        "First Set Winner",
        "Total Sets",
        "First Set Score",
        "1st Set Total Games",
        "Player To Win A Set",
        "First Break Of Serve",
        "Players First Service Game - Game Winner",
        "Players First Service Game - First Point",
        "Players First Service Game - Game Score",
        "Players First Service Game - Game to Deuce",
        "Players First Service Game - To Face Break Point",
        "Players First Service Game - Server to Win to 0/15",
        "Players First Service Game - Server to Win to 0/15/30",
        "Double Result",
        "Total Tie Breaks in Match",
        "Total Breaks of Serve in Match",
        "Ace Totals",
        "Double Fault Totals",
        "Go The Distance?"
    ],
    "Set": [
        "First Set Winner",
        "Set Betting",
        "First Set Score",
        "1st Set Total Games",
        "First Set Handicap",
        "First Set Correct Score Group",
        "First Set Score Any Player",
        "First Set Player To Break Serve",
        "First Set Race To (Games)",
        "First Set Lead After (Games)",
        "First Set Score After 4 Games",
        "First Set Score After 6 Games",
        "Total Sets",
        "First Set Player Breaks of Serve",
        "1st Set Total Breaks of Serve",
    ],
    "Games": [
        "Handicap 2-Way - Games Won",
        "Total Games 2-Way",
        "1st Set Total Games",
        "Player Games Won",
        "First Break Of Serve",
        "First Set Race To (Games)",
        "First Set Lead After (Games)",
        "First Set Score After 4 Games",
        "First Set Score After 6 Games",
        "Match Result and Total Games",
        "Match Total Games Odd/Even",
    ],
    "Player": [
        "Player Games Won",
        "Player To Win A Set",
        "Player To Win From Behind (Sets)",
        "To Win in Straight Sets",
        "First Break Of Serve",
        "Player Total Breaks of Serve in Match",
        "Players First Service Game - Game Winner",
        "Players First Service Game - First Point",
        "Players First Service Game - Game Score",
        "Players First Service Game - Game to Deuce",
        "Players First Service Game - To Face Break Point",
        "Players First Service Game - Total Points",
        "Players First Service Game - Score After 2 Points",
        "Players First Service Game - Score After 3 Points",
        "Players First Service Game - Score After 4 Points",
        "Players First Service Game - Server to Win to 0/15",
        "Players First Service Game - Server to Win to 0/15/30",
        "First Set Player To Break Serve",
    ]
}
