export const basketballMainMarkets = {
  gameLines: {
    marketname: "Game Lines",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "1stHalf": {
    marketname: "1st Half",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "1stQuarter": {
    marketname: "1st Quarter",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "2ndQuarter": {
    marketname: "2nd Quarter",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "3rdQuarter": {
    marketname: "3rd Quarter",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "4thQuarter": {
    marketname: "4th Quarter",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "gameLines3-Way": {
    marketname: "Game Lines 3-Way",
    suspend: "0",
    header: ["", "Home", "Tie", "Away"],
    rows: [],
  },
};

export const basketballBetBuilder = {
  spread: {
    marketname: "Spread",
    suspend: "0",
    subtabs: ["Match", "1st Half", "1t Quarter"],
    header: [],
    "Match header": ["Home", "Away"],
    Match: [],
    "1st Half header": ["Home", "Away"],
    "1st Half": [],
    "1st Quarter header": ["Home", "Away"],
    "1st Quarter": [],
  },
  total: {
    marketname: "Total",
    suspend: "0",
    subtabs: ["Match", "1st Half", "1t Quarter"],
    header: [],
    "Match header": ["", "Over", "Under"],
    Match: [],
    "1st Half header": ["", "Over", "Under"],
    "1st Half": [],
    "1st Quarter header": ["", "Over", "Under"],
    "1st Quarter": [],
  },
  moneyLine: {
    marketname: "Money Line",
    suspend: "0",
    header: ["", "Home", "Tie", "Away"],
    rows: [],
  },
  tiedAtEndOfRegulation: {
    marketname: "Toed At End Of Regulation",
    suspend: "0",
    header: [],
    rows: [],
  },
  resultAndBothTeamsToScore: {
    marketname: "Result and Both Teams to Score",
    suspend: "0",
    header: ["", "60 Points", "80 Points"],
    rows: [],
  },
  "half/Quarter-RaceTo": {
    marketname: "Half/Quarter - Race To",
    suspend: "0",
    subtabs: ["1st Half", "1st Quarter"],
    header: [],
    "1st Half header": ["", "Home", "Away", "Neither"],
    "1st Half": [],
    "1st Quarter header": ["", "Home", "Away", "Neither"],
    "1st Quarter": [],
  },
  "half/Quarter-BothTeamsToScoreXPoints": {
    marketname: "Half/Quarter - Both Teams to Score X Points",
    suspend: "0",
    subtabs: ["1st Half", "1st Quarter"],
    header: [],
    "1st Half header": ["", "Yes", "No"],
    "1st Half": [],
    "1st Quarter header": ["", "Yes", "No"],
    "1st Quarter": [],
  },
};

export const basketballMainProps = {
  alternativePointSpread: {
    marketname: "Alternative Point Spread",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativeGameTotal: {
    marketname: "Alternative Game Total",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativePointSpread2: {
    marketname: "Alternative Point Spread 2",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativeGameTotal2: {
    marketname: "Alternative Game Total 2",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  resultAndBothTeamsToScoreXPoints: {
    marketname: "Result and Both Teams to Score 'X' Points",
    suspend: "0",
    header: ["", "60", "80"],
    rows: [],
  },
  doubleResult: {
    marketname: "Double Result",
    suspend: "0",
    header: [],
    rows: [],
  },
  matchResultAndTotal: {
    marketname: "Match Result and Total",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  matchHandicapAndTotal: {
    marketname: "Match Handicap and Total",
    suspend: "0",
    header: [],
    rows: [],
  },
  winningMargin: {
    marketname: "Winning Margin",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  winningMargin3Way: {
    marketname: "Winning Margin 3-Way",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  winningMargin7Way: {
    marketname: "Winning Margin 7-Way",
    suspend: "0",
    header: ["", ""],
    rows: [],
  },
  winningMargin12Way: {
    marketname: "Winning Margin 12-Way",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  raceTo20Points: {
    marketname: "Race to 20 Points",
    suspend: "0",
    header: [],
    rows: [],
  },
  tiedAtEndOfRegulations: {
    marketname: "Tied at End of Regulation?",
    suspend: "0",
    header: [],
    rows: [],
  },
  quarterCorrectScore: {
    marketname: "Quarter Correct Score",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  highestScoringHalf: {
    marketname: "Highest Scoring Half",
    suspend: "0",
    header: [],
    rows: [],
  },
  highestScoringQuarter: {
    marketname: "Highest Scoring Quarter",
    suspend: "0",
    header: [],
    rows: [],
  },
  gameTotalBands8Way: {
    marketname: "Game Total (Bands) 8-Way",
    suspend: "0",
    header: [],
    rows: [],
  },
  gameTotalBands3Way: {
    marketname: "Game Total (Bands) 3-Way",
    suspend: "0",
    header: [],
    rows: [],
  },
  gameTotalOddEven: {
    marketname: "Game Total - Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
};

export const basketballTeamProps = {
  teamWithHighestScoringQuarter: {
    marketname: "Team With Higest Scoring Quarter",
    suspend: "0",
    header: [],
    rows: [],
  },
  teamTotals: {
    marketname: "Team Totals",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  homeAlternativeTeamTotals: {
    marketname: "Alternative Home Team Totals",
    suspend: "0",
    header: ["Home", "Over", "Under"],
    rows: [],
  },
  awayAlternativeTeamTotals: {
    marketname: "Alternative Away Team Totals",
    suspend: "0",
    header: ["Away", "Over", "Under"],
    rows: [],
  },
  homeAlternativeTeamTotals2: {
    marketname: "Alternative Home Team Totals 2",
    suspend: "0",
    header: ["Home", "Over", "Under"],
    rows: [],
  },
  awayAlternativeTeamTotals2: {
    marketname: "Alternative Away Team Totals 2",
    suspend: "0",
    header: ["Away", "Over", "Under"],
    rows: [],
  },
  "1stQuarterTeamTotals": {
    marketname: "1st Quarter Team Totals",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  homeAlternativeFirstQuarterTeamTotals: {
    marketname: "Alternative 1st Quarter Home Team Totals",
    suspend: "0",
    header: ["Home", "Over", "Under"],
    rows: [],
  },
  awayAlternativeFirstQuarterTeamTotals: {
    marketname: "Alternative 1st Quarter Away Team Totals",
    suspend: "0",
    header: ["Away", "Over", "Under"],
    rows: [],
  },
  "1stHalfTeamTotals": {
    marketname: "1st Half Team Totals",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  homeAlternativeFirstHalfTeamTotals: {
    marketname: "Alternative 1st Half Home Team Totals",
    suspend: "0",
    header: ["Home", "Over", "Under"],
    rows: [],
  },
  awayAlternativeFirstHalfTeamTotals: {
    marketname: "Alternative 1st Half Away Team Totals",
    suspend: "0",
    header: ["Away", "Over", "Under"],
    rows: [],
  },
  homeFirstQuarterTeamToScoreXPoint: {
    marketname: "1st Quarter Home Team To Score X Points",
    suspend: "0",
    header: ["Home", "Yes", "No"],
    rows: [],
  },
  awayFirstQuarterTeamToScoreXPoint: {
    marketname: "1st Quarter Away Team To Score X Points",
    suspend: "0",
    header: ["Away", "Yes", "No"],
    rows: [],
  },
  "teamTotal-Odd/Even": {
    marketname: "Team Total - Odd/Even",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  homeFirstHalfTeamToScoreXPoint: {
    marketname: "1st Half Home Team To Score X Points",
    suspend: "0",
    header: ["Home", "Yes", "No"],
    rows: [],
  },
  awayFirstHalfTeamToScoreXPoint: {
    marketname: "1st Half Away Team To Score X Points",
    suspend: "0",
    header: ["Away", "Yes", "No"],
    rows: [],
  },
};

export const basketballQuarterProps = {
  alternativeFirstQuarterPointSpread: {
    marketname: "Alternative 1st Quarter Point Spread",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativeFirstQuarterTotals: {
    marketname: "Alternative 1st Quarter Totals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  homeAlternativeFirstQuarterTeamTotals: {
    marketname: "Alternative 1st Quarter Home Team Totals",
    suspend: "0",
    header: ["Home", "Over", "Under"],
    rows: [],
  },
  awayAlternativeFirstQuarterTeamTotals: {
    marketname: "Alternative 1st Quarter Away Team Totals",
    suspend: "0",
    header: ["Away", "Over", "Under"],
    rows: [],
  },
  "1stQuarterBothTeamsToScoreXPoints": {
    marketname: "1st Quarter Both Teams to Score X Points",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  "1stQuarterDoubleChance": {
    marketname: "1st Quarter Double Chance",
    suspend: "0",
    header: [],
    rows: [],
  },
  "1stQuarterHandicapAndTotal": {
    marketname: "1st Quarter Handicap and Total",
    suspend: "0",
    header: [],
    rows: [],
  },
  "1stQuarterMarginofVictory": {
    marketname: "1st Quarter Margin Of Victory",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "1stQuarter3WayLines": {
    marketname: "1st Quarter 3 Way Lines",
    suspend: "0",
    header: ["", "Home", "Tie", "Away"],
    rows: [],
  },
  "1stQuarterRaceToPoints": {
    marketname: "1st Quarter Race To (Points)",
    suspend: "0",
    header: ["", "Home", "Away", "Neither"],
    rows: [],
  },
  "1stQuarterResultAndTotal": {
    marketname: "1st Quarter Result and Total",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  "1stQuarterTeamTotals": {
    marketname: "1st Quarter Team Totals",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  homeFirstQuarterTeamToScoreXPoint: {
    marketname: "1st Quarter Home Team To Score X Points",
    suspend: "0",
    header: ["Home", "Yes", "No"],
    rows: [],
  },
  awayFirstQuarterTeamToScoreXPoint: {
    marketname: "1st Quarter Away Team To Score X Points",
    suspend: "0",
    header: ["Away", "Yes", "No"],
    rows: [],
  },
  "1stQuarterTotal-Odd/Even": {
    marketname: "1st Quarter Total - Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
  "1stQuarterWinningMargin": {
    marketname: "1st Quarter Winning Margin",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
};

export const basketballHalfProps = {
  "1stHalfTeamTotals": {
    marketname: "1st Half Team Totals",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  homeAlternativeFirstHalfTeamTotals: {
    marketname: "Alternative 1st Half Home Team Totals",
    suspend: "0",
    header: ["Home", "Over", "Under"],
    rows: [],
  },
  awayAlternativeFirstHalfTeamTotals: {
    marketname: "Alternative 1st Half Away Team Totals",
    suspend: "0",
    header: ["Away", "Over", "Under"],
    rows: [],
  },
  alternativeFirstHalfPointSpread: {
    marketname: "Alternative 1st Half Point Spread",
    suspend: "0",
    header: ["Home", "Away"],
    rows: [],
  },
  alternativeFirstHalfTotals: {
    marketname: "Alternative 1st Half Totals",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  "1stHalfWinningMargin": {
    marketname: "1st Half Winning Margin",
    suspend: "0",
    header: ["", "Home", "Away"],
    rows: [],
  },
  "1stHalfResultAndTotal": {
    marketname: "1st Half Result and Total",
    suspend: "0",
    header: ["", "Over", "Under"],
    rows: [],
  },
  "1stHalfHandicapAndTotal": {
    marketname: "1st Half Handicap and Total",
    suspend: "0",
    header: [],
    rows: [],
  },
  "1stHalfRaceToPoints": {
    marketname: "1st Half Race to (Points)",
    suspend: "0",
    header: ["", "Home", "Away", "Neither"],
    rows: [],
  },
  "1stHalfBothTeamsToScoreXPoints": {
    marketname: "1st half Both Teams to Score X Points",
    suspend: "0",
    header: ["", "Yes", "No"],
    rows: [],
  },
  homeFirstHalfTeamToScoreXPoint: {
    marketname: "1st Half Home Team To Score X Points",
    suspend: "0",
    header: ["Home", "Yes", "No"],
    rows: [],
  },
  awayFirstHalfTeamToScoreXPoint: {
    marketname: "1st Half Away Team To Score X Points",
    suspend: "0",
    header: ["Away", "Yes", "No"],
    rows: [],
  },
  "1stHalfSpread3-Way": {
    marketname: "1st Half Spread 3-Way",
    suspend: "0",
    header: ["Home", "Tie", "Away"],
    rows: [],
  },
  "1stHalfTotals3-Way": {
    marketname: "1st Half Totals 3-Way",
    suspend: "0",
    header: ["","Over", "Exactly", "Under"],
    rows: [],
  },
  "1stHalfMoneyLine3-Way": {
    marketname: "1st Half Money Line 3-Way",
    suspend: "0",
    header: [],
    rows: [],
  },
  "1stHalfDoubleChance": {
    marketname: "1st Half Double Chance",
    suspend: "0",
    header: [],
    rows: [],
  },
  "1stHalfTotalOdd/Even": {
    marketname: "1st Half Total Odd/Even",
    suspend: "0",
    header: [],
    rows: [],
  },
};
