const whatItShouldBe = [
    "World: World Cup Women",
    "Finland: Veikkausliiga",
    "South Korea: K League 2",
    "Ireland: Fai Cup",
    "England: Fa Community Shield",
    "Europe: Uefa Super Cup",
    "England: Premier League",
    "Poland: Ekstraklasa",
    "England: Championship",
    "England: League One",
    "England: League Two",
    "England: Efl Cup",
    "South Korea: K League 1",
    "Spain: Laliga",
    "Austria: Bundesliga",
    "Romania: Liga 1",
    "Germany: Bundesliga",
    "Denmark: Superliga",
    "Germany: 2. Bundesliga",
    "Scotland: Premiership",
    "France: Ligue 1",
    "Belgium: Jupiler Pro League",
    "North &amp; Central America: Leagues Cup",
    "Poland: Division 1",
    "Switzerland: Super League",
    "Hungary: Otp Bank Liga",
    "Denmark: 1st Division",
    "Netherlands: Super Cup",
    "Italy: Serie A",
    "England: National League",
    "Netherlands: Eredivisie",
    "Belgium: Super Cup",
    "Czech Republic: Division 2",
    "Norway: Eliteserien",
    "Estonia: Meistriliiga",
    "Latvia: Optibet Virsliga",
    "Finland: Kakkonen Group B",
    "France: Ligue 2",
    "Sweden: Allsvenskan",
    "Switzerland: Challenge League",
    "Brazil: Serie A",
    "Sweden: Superettan",
    "Poland: Division 2",
    "Australia: Npl Western Australia",
    "Australia: Npl Northern Nsw",
    "USA: Usl Championship",
    "Australia: Npl Queensland",
    "Colombia: Primera B - Clausura",
    "South America: Copa Sudamericana - Play Offs",
    "Norway: Obos-Ligaen",
    "Peru: Liga 1 - Clausura",
    "Finland: Ykkonen",
    "Austria: Ofb Cup",
    "Iceland: Besta Deild Karla",
    "Croatia: Hnl",
    "Australia: Npl Nsw",
    "Australia: Npl Victoria",
    "Uruguay: Primera Division - Torneo Intermedio",
    "Japan: J3 League",
    "Australia: Npl Act",
    "Europe: Europa Conference League - Qualification",
    "Slovenia: Prva Liga",
    "Mexico: Liga De Expansion Mx - Apertura",
    "Japan: J2 League",
    "Japan: J1 League",
    "Brazil: Serie B",
    "Chile: Primera Division",
    "China: Super League",
    "Bulgaria: Parva Liga",
    "Argentina: Liga Profesional",
    "Ireland: Division 1",
    "Ireland: Premier Division",
    "Colombia: Primera A - Clausura",
    "Paraguay: Primera Division - Clausura",
    "World: Club Friendly",
    "Argentina: Copa Argentina",
    "Austria: 2. Liga",
    "Brazil: Serie C - First Stage",
    "Greece: Super League",
    "Lithuania: A Lyga",
    "Argentina: Primera Nacional",
    "Scotland: League Cup",
    "Iceland: Division 1",
    "Bolivia: League Cup",
    "Germany: Regionalliga Bayern",
    "Israel: Toto Cup - Qualification - Play Offs",
    "Bulgaria: Vtora Liga",
    "Brazil: Campeonato Carioca 2",
    "Ecuador: Serie B",
    "Brazil: Brasileiro U20 - Play Offs",
    "Panama: Lpf - Clausura",
    "Venezuela: Liga Futve",
    "Indonesia: Liga 1",
    "South Korea: K3 League",
    "Malaysia: Super League",
    "Iraq: Super League",
    "Singapore: Premier League",
    "Europe: Euro U19 Women",
    "Myanmar: National League",
    "Germany: Oberliga Bayern Nord",
    "Norway: Division 2 - Group 2",
    "USA: Mls Next Pro",
    "Wales: League Cup",
    "Portugal: League Cup - First Stage",
    "USA: Usl League Two - Play Offs",
    "Brazil: Copa Paulista",
    "USA: Nwsl Challenge Cup Women",
    "World: Friendly International",
    "Chile: Primera B",
    "Mexico: Liga Mx Women - Apertura",
    "Bolivia: Division Profesional",
    "China: Jia League",
    "China: Yi League",
    "Dominican Republic: Ldf - Winners Stage",
    "Canada: Canadian Premier League",
    "Finland: Kansallinen Liiga Women",
    "Jordan: Super Cup",
    "Estonia: Esiliiga",
    "Vietnam: V.League 1 - Championship Group",
    "Vietnam: V.League 2",
    "Iceland: Division 2",
    "Latvia: 1. Liga",
    "Scotland: Lowland League",
    "Zimbabwe: Premier Soccer League",
    "Malawi: Super League",
    "Kazakhstan: Premier League",
    "Israel: Super Cup",
    "Norway: Division 3 - Group 4",
    "USA: Usl League One",
    "Malaysia: Fa Cup",
    "Kenya: Premier League - Relegation",
    "Mozambique: Mocambola",
    "Brazil: Serie D",
    "World: Club Friendly Women",
    "Uruguay: Segunda Division",
    "Egypt: League Cup",
    "Germany: Oberliga Bayern Süd",
    "Finland: Kakkonen Group C",
    "Montenegro: Prva Crnogorska Liga",
    "Chile: Segunda Division",
    "Argentina: Primera B - Clausura",
    "Argentina: Primera D - Second Stage",
    "Brazil: Campeonato Mineiro 2 - Final Stage",
    "Argentina: Torneo Federal",
    "Argentina: Primera C",
    "Egypt: Premier League",
    "Czech Republic: 1. Liga",
    "Venezuela: Liga Futve 2 - Clausura",
    "Brazil: Campeonato Catarinense 2",
    "Senegal: Ligue 1",
    "Czech Republic: Mol Cup",
    "Vietnam: V.League 1 - Relegation Group",
    "Europe: Champions League - Qualification",
    "Finland: Kakkonen Group A",
    "Norway: Division 3 - Group 6",
    "Brazil: Campeonato Gaucho 2 - Play Offs",
    "Norway: Division 3 - Group 5",
    "Brazil: Campeonato Paranaense 2 - Play Offs",
    "Brazil: Copa Do Brasil",
    "India: Calcutta Premier Division",
    "Peru: Liga 2",
    "Lebanon: Federation Cup - Play Offs",
    "Costa Rica: Primera Division - Apertura",
    "Colombia: Copa Colombia",
    "Australia: Npl Tasmania",
    "Germany: Regionalliga Nordost",
    "World: Arab Club Champions Cup",
    "Europe: Euro U19 Women - Play Offs",
    "Faroe Islands: Premier League",
    "Wales: Cymru South",
    "Estonia: Estonian Cup",
    "Uzbekistan: Super League",
    "Australia: Npl South Australian",
    "Chile: Chilean Cup",
    "Ukraine: Premier League",
    "USA: Nisa",
    "South America: Copa Libertadores - Play Offs",
    "Sweden: Division 1 - Norra"
]

export const Correction = {
    "Women's World Cup": "World: World Cup Women",
    "Elite Club Friendlies": "",
    "UK Friendles": "",
    "UEFA Super Cup": "Europe: Uefa Super Cup",
    "UEFA Conference League Qualifying": "Europe: Europa Conference League - Qualification",
    "World Cup Women": "World: World Cup Women",
    "Club Friendly": "World: Club Friendly",
    "Friendly International": "World: Friendly International",
    "Club Friendly Women": "World: Club Friendly Women",
    "Arab Club Champions Cup": "World: Arab Club Champions Cup",
    "Copa Sudamericana - Play Offs": "South America: Copa Sudamericana - Play Offs",
    "Copa Libertadores - Play Offs": "South America: Copa Libertadores - Play Offs",
    "Leagues Cup": "North &amp; Central America: Leagues Cup",
}


export const Categoryoptions = {
    "Main Markets": [
        "Game Lines",
        "5 Innings",
        "3-Way",
    ],
}

